title: Yoko's Kitchen
description: ""
destination: docs
baseurl: "/yokos-kitchen-hw"
url: ""
twitter_username: jekyllrb
github_username:  jekyll

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .node_modules
  - .node_modules/
  - .gitignore
  - package-lock.json
  - package.json
  - gulpfile.js
  - ._data/